"""baseline from existing database

Revision ID: 06e149eac367
Revises: 
Create Date: 2026-02-02 14:58:46.378698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e149eac367'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FREQUENCE',
    sa.Column('id_frequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle_frequence', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_frequence'),
    schema='dbo'
    )
    op.create_table('ROUTINE_LOG',
    sa.Column('id_routine_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_routine', sa.String(length=50), nullable=True),
    sa.Column('description_routine', sa.String(length=255), nullable=True),
    sa.Column('libelle_frequence', sa.String(length=50), nullable=True),
    sa.Column('date_execution_routine_log', sa.Date(), nullable=True),
    sa.Column('commentaire_routine_log', sa.String(length=255), nullable=True),
    sa.Column('image_path_log', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_routine_log'),
    schema='dbo'
    )
    op.create_table('ROUTINE',
    sa.Column('id_routine', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_routine', sa.String(length=50), nullable=False),
    sa.Column('description_routine', sa.String(length=255), nullable=True),
    sa.Column('jour_semaine_routine', sa.Integer(), nullable=True),
    sa.Column('jour_mois_routine', sa.Integer(), nullable=True),
    sa.Column('mois_routine', sa.Integer(), nullable=True),
    sa.Column('date_creation_routine', sa.Date(), nullable=True),
    sa.Column('lien', sa.String(length=255), nullable=True),
    sa.Column('last_commentaire', sa.String(length=255), nullable=True),
    sa.Column('last_date_execution', sa.Date(), nullable=True),
    sa.Column('id_frequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_frequence'], ['dbo.FREQUENCE.id_frequence'], ),
    sa.PrimaryKeyConstraint('id_routine'),
    schema='dbo'
    )
    op.create_table('ROUTINE_JOUR',
    sa.Column('id_routine_jour', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_routine_jour', sa.Date(), nullable=True),
    sa.Column('statut_routine_jour', sa.Integer(), nullable=True),
    sa.Column('commentaire_routine_jour', sa.String(length=255), nullable=True),
    sa.Column('image_path_jour', sa.String(length=255), nullable=True),
    sa.Column('id_routine', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_routine'], ['dbo.ROUTINE.id_routine'], ),
    sa.PrimaryKeyConstraint('id_routine_jour'),
    sa.UniqueConstraint('id_routine', 'date_routine_jour', name='uq_routine_jour_routine_date'),
    schema='dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ROUTINE_JOUR', schema='dbo')
    op.drop_table('ROUTINE', schema='dbo')
    op.drop_table('ROUTINE_LOG', schema='dbo')
    op.drop_table('FREQUENCE', schema='dbo')
    # ### end Alembic commands ###
